cacheLocation = "cache.yaml"
username = "<username>"
password = "<password>"

[emulator]
blueStacksHome = "C:/Program Files/BlueStacks_nxt"
blueStacksData = "C:/ProgramData/BlueStacks_nxt"
instance = "Nougat32"
adbHost = "127.0.0.1"
adbPort = 0